name: Sync-to-partner-repo
on:
  push:
    branches:
      - 'partner/crazyhunter**'

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    environment: prd
    env:
      SYNC_REPO_OWNER: "unity"
      SYNC_REPO_NAME: "bonfire-unity-graphics-sync"
      SYNC_API_URL: "https://api.github.cds.internal.unity3d.com"
      SYNC_WORKFLOW_PATH: "main.yml"
      SYNC_WORKFLOW_BRANCH: "gh-action"
      PUSHED_REPO: "foo"
      PUSHED_BRANCH: "bar"
    steps:
      - name: Trigger Yamato sync
        run: |
            sync_workflow_dispatch_endpoint="${SYNC_API_URL}/repos/${SYNC_REPO_OWNER}/${SYNC_REPO_NAME}/actions/workflows/${SYNC_WORKFLOW_PATH}/dispatches"


            curl -k "${sync_workflow_dispatch_endpoint}" \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Content-Type: application/json" \
                -u "${GH_CDS_USER}:${GH_CDS_TOKEN}" \
                --data \
                    "{
                        \"ref\"                  : \"${SYNC_WORKFLOW_BRNACH}\",
                        \"inputs\"               : {
                            \"PUSHED_REPO\"   : \"${PUSHED_REPO}\",
                            \"PUSHED_BRANCH\" : \"${PUSHED_BRANCH}\"
                        }
                    }"

